baseURL: http://bulletproofpancake.github.io/
languageCode: en-us
title: ReadLine
theme: "PaperMod"

enableGitInfo: true

params:
  author: ["Jolo Gutierrez"]

  assets:
    favicon16x16: "https://i.imgur.com/ionarhS.png"
    favicon32x32: "https://i.imgur.com/Jo1I9xQ.png"

  profileMode:
    enabled: true
    title: "Jolo Gutierrez" # optional default will be site title
    subtitle: "Game Developer. Batangueño."
    imageUrl: "https://i.imgur.com/ae6QJsY.jpg" # optional
    imageTitle: "ProfilePic" # optional
    imageWidth: 240 # custom size
    imageHeight: 240 # custom size

  socialIcons:
    - name: Github
      url: "https://github.com/bulletproofpancake/"
    - name: itchio
      url: "https://bulletproofpancake.itch.io/"
    - name: linkedin
      url: "https://www.linkedin.com/in/mjgutierreziii"
    - name: email
      url: "mailto:jgutierrez1100@gmail.com"
    - name: discord
      url: "https://www.discord.com/users/592223470763638784"

  editPost:
    URL: "https://github.com/bulletproofpancake/bulletproofpancake.github.io/blob/main/content"
    Text: "Suggest Changes" # edit text
    appendFilePath: true # to append file path to Edit link

  ShowPostNavLinks: true

  ShowBreadCrumbs: true

  ShowCodeCopyButtons: true

  ShowReadingTime: true

  ShowShareButtons: true

  ShowToc: true

  ShareButtons: ["linkedin", "reddit", "twitter", "facebook"]

menu:
  main:
    - name: About Me
      url: /about/
    - name: Posts
      url: "posts/"
